apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg
data:
  MYSQL_HOST: db
  MYSQL_DATABASE: nextcloud
  MYSQL_USER: nextcloud
  MYSQL_PASSWORD: nextcloud
  MYSQL_ROOT_PASSWORD: nextcloud
  REDIS_HOST: redis
